Lab1/Controllers/PhotosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lab1.Models;

namespace Lab1.Controllers
{
    public class PhotosController : Controller
    {
        private ContextModel db = new ContextModel();

        // GET: Photos
        public ActionResult Index(int? id)
        {
            if(id == null)
            {
                return View(db.Photos.Include(a => a.Apartments).ToList());
            }
            else
            {
                return View(db.Photos.Include(a => a.Apartments).Where(x => x.Apartments.Id == id).ToList());
            }
        }

        // GET: Photos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photos photos = db.Photos.Find(id);
            if (photos == null)
            {
                return HttpNotFound();
            }
            return View(photos);
        }

        // GET: Photos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Photos/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Photo")] Photos photos)
        {
            if (ModelState.IsValid)
            {
                db.Photos.Add(photos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(photos);
        }

        // GET: Photos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photos photos = db.Photos.Find(id);
            if (photos == null)
            {
                return HttpNotFound();
            }
            return View(photos);
        }

        // POST: Photos/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Photo")] Photos photos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(photos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(photos);
        }

        // GET: Photos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Photos photos = db.Photos.Find(id);
            if (photos == null)
            {
                return HttpNotFound();
            }
            return View(photos);
        }

        // POST: Photos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Photos photos = db.Photos.Find(id);
            db.Photos.Remove(photos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Lab1/Controllers/RegisterNewLivingController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web.Mvc;
using Lab1.Models;

namespace Lab1.Controllers
{
    public class RegisterNewLivingController : Controller
    {
        private ContextModel db = new ContextModel();

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ChooseDate([Bind(Include = "Settling,Eviction,ValueOfGuests,ValueOfKids,ClientId")] Living living)
        {
            if (ModelState.IsValid)
            {
                ViewBag.LivingId = living.Id;
                ViewBag.Settling = living.Settling;
                ViewBag.Eviction = living.Eviction;
                ViewBag.ValueOfGuests = living.ValueOfGuests;
                ViewBag.ValueOfKids = living.ValueOfKids;
                ViewBag.ClientId = living.ClientId;
                string settlingStr = ConvertDateToString(living.Settling);
                string evictionStr = ConvertDateToString(living.Eviction);
                var requestResultTest = db.Apartments.SqlQuery($"SELECT * FROM Apartments b WHERE EXISTS (SELECT a.id FROM Apartments a WHERE b.id = a.id AND a.price > {0} AND a.price < {999999} AND (( EXISTS (SELECT apartmentsid FROM Livings WHERE eviction < '{settlingStr}' AND apartmentsid = a.id) AND NOT EXISTS(SELECT apartmentsid FROM Bookings WHERE EXISTS (SELECT apartmentsid FROM Bookings WHERE apartmentsid = a.id))) OR (EXISTS (SELECT apartmentsid FROM Bookings WHERE settling > '{evictionStr}' AND apartmentsid = a.id) OR ( EXISTS (SELECT apartmentsid FROM Bookings WHERE eviction < '{settlingStr}' AND apartmentsid = a.id))) AND NOT EXISTS(SELECT apartmentsid FROM Livings WHERE EXISTS (SELECT apartmentsid FROM Livings WHERE apartmentsid = a.id)) OR (( EXISTS (SELECT apartmentsid FROM Livings WHERE eviction<'{settlingStr}' AND apartmentsid = a.id)) AND ( EXISTS (SELECT apartmentsid FROM Bookings WHERE settling>'{evictionStr}' AND apartmentsid = a.id ) OR ( EXISTS (SELECT apartmentsid FROM Bookings WHERE eviction<'{settlingStr}' AND apartmentsid = a.id)))) OR ( NOT EXISTS (SELECT apartmentsid FROM Livings WHERE apartmentsid = a.id) AND NOT EXISTS (SELECT apartmentsid FROM Bookings WHERE apartmentsid = a.id))))");
                //var requestRT = db.Apartments.($"SELECT * FROM Apartments b WHERE EXISTS (SELECT a.id FROM Apartments a WHERE b.id = a.id AND a.price > {0} AND a.price < {999999} AND (( EXISTS (SELECT apartmentsid FROM Livings WHERE eviction < '{settlingStr}' AND apartmentsid = a.id) AND NOT EXISTS(SELECT apartmentsid FROM Bookings WHERE EXISTS (SELECT apartmentsid FROM Bookings WHERE apartmentsid = a.id))) OR (EXISTS (SELECT apartmentsid FROM Bookings WHERE settling > '{evictionStr}' AND apartmentsid = a.id) OR ( EXISTS (SELECT apartmentsid FROM Bookings WHERE eviction < '{settlingStr}' AND apartmentsid = a.id))) AND NOT EXISTS(SELECT apartmentsid FROM Livings WHERE EXISTS (SELECT apartmentsid FROM Livings WHERE apartmentsid = a.id)) OR (( EXISTS (SELECT apartmentsid FROM Livings WHERE eviction<'{settlingStr}' AND apartmentsid = a.id)) AND ( EXISTS (SELECT apartmentsid FROM Bookings WHERE settling>'{evictionStr}' AND apartmentsid = a.id ) OR ( EXISTS (SELECT apartmentsid FROM Bookings WHERE eviction<'{settlingStr}' AND apartmentsid = a.id)))) OR ( NOT EXISTS (SELECT apartmentsid FROM Livings WHERE apartmentsid = a.id) AND NOT EXISTS (SELECT apartmentsid FROM Bookings WHERE apartmentsid = a.id))))");
                //DbSqlQuery
                DbSqlQuery<Apartments> apartmentsQuery = db.Apartments.SqlQuery($"SELECT * FROM Apartments b WHERE EXISTS (SELECT a.id FROM Apartments a WHERE b.id = a.id AND a.price > {0} AND a.price < {999999} AND (( EXISTS (SELECT apartmentsid FROM Livings WHERE eviction < '{settlingStr}' AND apartmentsid = a.id) AND NOT EXISTS(SELECT apartmentsid FROM Bookings WHERE EXISTS (SELECT apartmentsid FROM Bookings WHERE apartmentsid = a.id))) OR (EXISTS (SELECT apartmentsid FROM Bookings WHERE settling > '{evictionStr}' AND apartmentsid = a.id) OR ( EXISTS (SELECT apartmentsid FROM Bookings WHERE eviction < '{settlingStr}' AND apartmentsid = a.id))) AND NOT EXISTS(SELECT apartmentsid FROM Livings WHERE EXISTS (SELECT apartmentsid FROM Livings WHERE apartmentsid = a.id)) OR (( EXISTS (SELECT apartmentsid FROM Livings WHERE eviction<'{settlingStr}' AND apartmentsid = a.id)) AND ( EXISTS (SELECT apartmentsid FROM Bookings WHERE settling>'{evictionStr}' AND apartmentsid = a.id ) OR ( EXISTS (SELECT apartmentsid FROM Bookings WHERE eviction<'{settlingStr}' AND apartmentsid = a.id)))) OR ( NOT EXISTS (SELECT apartmentsid FROM Livings WHERE apartmentsid = a.id) AND NOT EXISTS (SELECT apartmentsid FROM Bookings WHERE apartmentsid = a.id))))");
                List<Apartments> apartments = new List<Apartments>();
                foreach (Apartments apt in apartmentsQuery.ToList())
                {
                    apartments.Add(db.Apartments.Include(a => a.ApartmentType).ToList().Find(x => x.Id == apt.Id));
                }
                return View("~/Views/RegisterNewLiving/LivingAvailableApartments.cshtml", apartments);
            }

            return View("~/Views/RegisterNewLiving/LivingDateChooser.cshtml");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FinishTheRegistration(int? ApartmentId, int? LivingId, int? ClientId, DateTime? Settling, DateTime? Eviction, int? ValueOfGuests, int? ValueOfKids)
        {
            Apartments currentApartment = db.Apartments.Include(a => a.ApartmentType).Where(x => x.Id == ApartmentId).First();
            Client currentClient = db.Clients.Include(l => l.Livings).Include(l => l.Livings).Where(x => x.Id == ClientId).First();

            Living currentLiving = new Living();
            currentLiving.Id = (int)LivingId;
            currentLiving.ApartmentsId = ApartmentId;
            currentLiving.ClientId = ClientId;
            currentLiving.Settling = (DateTime)Settling;
            currentLiving.Eviction = (DateTime)Eviction;
            currentLiving.ValueOfGuests = (int)ValueOfGuests;
            currentLiving.ValueOfKids = (int)ValueOfKids;

            if ((currentClient.Bookings.Count + currentClient.Livings.Count) < 6)
            {
                db.Livings.Add(currentLiving);
                db.SaveChanges();
            }
            return RedirectToAction("Index", "Livings", new { });
        }

        public String ConvertDateToString(DateTime? dt)
        {
            if (dt != null)
            {
                string processingStr = dt.ToString();
                processingStr = processingStr.Substring(0, 10);
                string day = processingStr.Substring(0, 2);
                string month = processingStr.Substring(3, 2);
                string year = processingStr.Substring(6, 4);
                return year + "-" + month + "-" + day;
            }
            return ConvertDateToString(DateTime.Today);
        }
    }
}

Lab1/Views/RegisterNewLiving/LivingAvailableApartments.cshtml
@model IEnumerable<Lab1.Models.Apartments>
@{
    ViewBag.Title = "BookingAvailableApartments";
}

<h2>Доступные номера</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Номер")
        </th>
        <th>
            @Html.DisplayName("Цена за сутки")
        </th>
        <th>
            @Html.DisplayName("Тип апартаментов")
        </th>
        <th>
            @Html.DisplayName("Вместимость номера")
        </th>
        <th>
            @Html.DisplayName("Фотографии")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        using (Html.BeginForm("FinishTheRegistration", "RegisterNewBooking", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Number, new { htmlAttributes = new { @class = "form-control" } })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price, new { htmlAttributes = new { @class = "form-control" } })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApartmentType.Type, new { htmlAttributes = new { @class = "form-control" } })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApartmentType.Capacity, new { htmlAttributes = new { @class = "form-control" } })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Photos, new { htmlAttributes = new { @class = "form-control" } })
                </td>
                <td>
                    @Html.ActionLink("Фотографии", "Index", "Photos", new { id = ViewBag.ClientId }, new { })
                </td>
                <td>
                    @*Не понятно, почему при передачи модели через форму передаётся null*@
                    @Html.Editor("ApartmentId", new { htmlAttributes = new { @class = "form-control", @style = "display:none", @Value = item.Id } })
                    @Html.Editor("LivingId", new { htmlAttributes = new { @class = "form-control", @style = "display:none", @Value = ViewBag.LivingId } })
                    @Html.Hidden("ClientId", new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.ClientId } })
                    @Html.Hidden("Settling", new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.Settling } })
                    @Html.Hidden("Eviction", new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.Eviction } })
                    @Html.Hidden("ValueOfGuests", new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.ValueOfGuests } })
                    @Html.Hidden("ValueOfKids", new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.ValueOfKids } })
                    @*@Html.EditorFor(modelItem => item, new { htmlAttributes = new { @class = "form-control", @style = "display:none" } })*@


                    @*@Html.ActionLink("Выбрать", "FinishTheRegistration", new { apartments = item })*@
                    <input type="submit" value="Выбрать" class="btn btn-default" />
                </td>
            </tr>
        }
    }
</table>

Lab1/Views/RegisterNewLiving/LivingDateChooser.cshtml
@model Lab1.Models.Living

@{
    ViewBag.Title = "ChooseDate";
}

<h2>Выбор даты</h2>

@using (Html.BeginForm("ChooseDate", "RegisterNewBooking"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Брони</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Дата заселения", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Settling, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Settling, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Дата выселения", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Eviction, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Eviction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Количество гостей", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValueOfGuests, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValueOfGuests, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Количество детей", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValueOfKids, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValueOfKids, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.Editor("ClientId", new { htmlAttributes = new { @class = "form-control", @style = "display:none", @Value = ViewBag.ClientId } })
                @Html.ValidationMessageFor(model => model.Client.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}