Lab1/Controllers/ApartmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lab1.Models;
using Lab1.Models.DataViewModels;

namespace Lab1.Controllers
{
    public class ApartmentsController : Controller
    {
        private ContextModel db = new ContextModel();

        // GET: Apartments
        public ActionResult Index()
        {
            return View(db.Apartments.Include(a => a.ApartmentType).Include(p => p.Photos).ToList());
        }

        // GET: Apartments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Apartments apartments = db.Apartments.Include(a => a.ApartmentType).ToList().Find(x => x.Id == id);
            if (apartments == null)
            {
                return HttpNotFound();
            }
            return View(apartments);
        }

        // GET: Apartments/Create
        public ActionResult Create()
        {
            ApartmentsTypeDataLogistics();

            return View();
        }

        // POST: Apartments/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Number,Price,ApartmentTypeId")] Apartments apartments)
        {
            foreach (Apartments n in db.Apartments.ToList())
            {
                //Проверка номера апартаментов на уникальность
                if (apartments.Number == n.Number)
                {
                    ModelState.AddModelError("Number", "Апартаменты с таким номером уже зарегистрированы");
                }
            }

            if (ModelState.IsValid)
            {
                db.Apartments.Add(apartments);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(apartments);
        }

        // GET: Apartments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Apartments apartments = db.Apartments.Include(a => a.ApartmentType).ToList().Find(x => x.Id == id);
            if (apartments == null)
            {
                return HttpNotFound();
            }

            ApartmentsTypeDataLogistics();

            return View(apartments);
        }

        // POST: Apartments/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Number,Price,ApartmentTypeId")] Apartments apartments)
        {
            foreach (Apartments n in db.Apartments.AsNoTracking().ToList())
            {
                //Проверка номера апартаментов на уникальность
                if ((apartments.Number == n.Number) && (apartments.Id != n.Id))
                {
                    ModelState.AddModelError("Number", "Апартаменты с таким номером уже зарегистрированы");
                }
            }

            if (ModelState.IsValid)
            {
                db.Entry(apartments).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(apartments);
        }

        // GET: Apartments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Apartments apartments = db.Apartments.Include(a => a.ApartmentType).ToList().Find(x => x.Id == id);
            if (apartments == null)
            {
                return HttpNotFound();
            }
            return View(apartments);
        }

        // POST: Apartments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Apartments apartments = db.Apartments.Find(id);
            db.Apartments.Remove(apartments);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private void ApartmentsTypeDataLogistics()
        {
            List<ApartmentType> listApartmentType = db.ApartmentTypes.ToList();
            List<DataViewApartmentType> viewApartmentType = new List<DataViewApartmentType>();
            foreach (var item in listApartmentType)
            {
                viewApartmentType.Add(new DataViewApartmentType()
                {
                    ApartmentTypeId = item.Id,
                    ApartmentTypeName = item.Type,
                });
            }
            ViewBag.ApartmentType = new SelectList(viewApartmentType, "ApartmentTypeId", "ApartmentTypeName");
        }
        //private void ApartmentsCapacityDataLogistics()
        //{
        //    List<ApartmentType> listApartmentType = db.ApartmentTypes.ToList();
        //    List<DataViewApartmentType> viewApartmentCapacity = new List<DataViewApartmentType>();
        //    foreach (var item in listApartmentType)
        //    {
        //        viewApartmentCapacity.Add(new DataViewApartmentType()
        //        {
        //            ApartmentTypeId = item.Id,
        //            ApartmentTypeCapacity = item.Capacity
        //        });
        //    }
        //    ViewBag.ApartmentCapacity = new SelectList(viewApartmentCapacity, "ApartmentTypeId", "ApartmentTypeCapacity");
        //}
    }
}

Lab1/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lab1.Models;

namespace Lab1.Controllers
{
    public class ClientsController : Controller
    {
        private ContextModel db = new ContextModel();

        // GET: Clients
        public ActionResult Index()
        {
            return View(db.Clients.Include(l => l.Livings).Include(b => b.Bookings).ToList());
        }

        // GET: Clients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Clients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Surname,Name,Patronymic,PassportNumber,PassportSeries,Birgthday,Telephone")] Client client)
        {
            IEnumerable<Client> listOfClients = db.Clients;
            foreach (Client c in listOfClients)
            {
                //Проверка пасспортных данных на уникальность
                if (client.PassportNumber == c.PassportNumber && client.PassportSeries == c.PassportSeries)
                {
                    ModelState.AddModelError("PassportSeries", "Клиент с такими серией или номером паспорта уже зарегистрирован");
                }

                //Проверка телефона на уникальность
                if (client.Telephone == c.Telephone)
                {
                    ModelState.AddModelError("Telephone", "Клиент с таким телефоном уже зарегистрирован");
                }
            }

            if (ModelState.IsValid)
            {
                db.Clients.Add(client);
                db.SaveChanges();
                ViewBag.ClientId = client.Id;
                //return RedirectToAction("BookingDateChooser", "Bookings", new { id = cId});
                return View("~/Views/RegisterNewBooking/BookingDateChooser.cshtml");
                //return RedirectToAction("Create", "Bookings", new { id = db.Clients.First(c => c.PassportSeries == client.PassportSeries && c.PassportNumber == client.PassportNumber).Id });
            }

            return View(client);
        }

        // GET: Clients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Surname,Name,Patronymic,PassportNumber,PassportSeries,Birgthday,Telephone")] Client client)
        {
            foreach (Client c in db.Clients.AsNoTracking().ToList())
            {
                //Проверка пасспортных данных на уникальность
                if ((client.PassportNumber == c.PassportNumber && client.PassportSeries == c.PassportSeries) && (client.Id != c.Id))
                {
                    ModelState.AddModelError("PassportSeries", "Клиент с такими серией или номером паспорта уже зарегистрирован");
                }

                //Проверка телефона на уникальность
                if ((client.Telephone == c.Telephone) && (client.Id != c.Id))
                {
                    ModelState.AddModelError("Telephone", "Клиент с таким телефоном уже зарегистрирован");
                }
            }

            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Client client = db.Clients.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Client client = db.Clients.Find(id);
            db.Clients.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [HttpPost]
        public ActionResult SearchWithValues(string searchableName, string searchableSurname, string searchablePatronymic, string searchableTelephone)
        {    
            IEnumerable<Client> listOfClients  = db.Clients;
            var clients = from linqC in db.Clients /*where linqC.Name == searchableName && linqC.Surname == searchableSurname && linqC.Patronymic == searchablePatronymic && linqC.Telephone == searchableTelephone*/ select linqC;
            if (!string.IsNullOrEmpty(searchableName))
                clients = clients.Where(c => c.Name.Contains(searchableName));
            if (!string.IsNullOrEmpty(searchableSurname))
                clients = clients.Where(с => с.Surname.Contains(searchableSurname));
            if (!string.IsNullOrEmpty(searchablePatronymic))
                clients = clients.Where(c => c.Patronymic.Contains(searchablePatronymic));
            if (!string.IsNullOrEmpty(searchableTelephone))
                clients = clients.Where(c => c.Telephone.Contains(searchableTelephone));
            return View("Index", clients);
        }

        public ActionResult AddLiving(int id)
        {
            if (ModelState.IsValid)
            {
                Client client = db.Clients.Find(id);
                ViewBag.ClientId = client.Id;
                //return RedirectToAction("BookingDateChooser", "Bookings", new { id = cId});
                return View("~/Views/RegisterNewLiving/LivingDateChooser.cshtml");
                //return RedirectToAction("Create", "Bookings", new { id = db.Clients.First(c => c.PassportSeries == client.PassportSeries && c.PassportNumber == client.PassportNumber).Id });
            }

            return View("Index");
        }

        public ActionResult AddBooking(int id)
        {
            if (ModelState.IsValid)
            {
                Client client = db.Clients.Find(id);
                ViewBag.ClientId = client.Id;
                //return RedirectToAction("BookingDateChooser", "Bookings", new { id = cId});
                return View("~/Views/RegisterNewBooking/BookingDateChooser.cshtml");
                //return RedirectToAction("Create", "Bookings", new { id = db.Clients.First(c => c.PassportSeries == client.PassportSeries && c.PassportNumber == client.PassportNumber).Id });
            }

            return View("Index");
        }

        public ActionResult MoveToLivings(int id)
        {
            if (ModelState.IsValid)
            {
                Client client = db.Clients.Find(id);
                ViewBag.ClientId = client.Id;
                int cId = client.Id;
                return RedirectToAction("Index", "Livings", new { id = cId});
                //return View("~/Views/RegisterNewBooking/BookingDateChooser.cshtml");
                //return RedirectToAction("Create", "Bookings", new { id = db.Clients.First(c => c.PassportSeries == client.PassportSeries && c.PassportNumber == client.PassportNumber).Id });
            }

            return View("Index");
        }

        public ActionResult MoveToBookings(int id)
        {
            if (ModelState.IsValid)
            {
                Client client = db.Clients.Find(id);
                ViewBag.ClientId = client.Id;
                int cId = client.Id;
                return RedirectToAction("Index", "Bookings", new { id = cId });
                //return View("~/Views/RegisterNewBooking/BookingDateChooser.cshtml");
                //return RedirectToAction("Create", "Bookings", new { id = db.Clients.First(c => c.PassportSeries == client.PassportSeries && c.PassportNumber == client.PassportNumber).Id });
            }

            return View("Index");
        }
    }
}

Lab1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab1.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
    }
}

Lab1/Views/Home/About.cshtml
@{
    ViewBag.Title = "О нас";
}
<h2>@ViewBag.Title.</h2>
<br />
<br />
<p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam at dolor eu turpis dapibus ultrices vitae et arcu. Donec ut maximus justo. Nam eu elit sit amet neque aliquet molestie in ac magna. Etiam sodales neque aliquet sem placerat commodo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris ac nunc tristique, auctor turpis sed, posuere nibh. Suspendisse ut lorem pharetra lorem hendrerit cursus.

    Nunc lacus justo, iaculis sit amet accumsan eget, molestie ut odio. Vivamus magna sapien, hendrerit at lacinia et, lacinia in ex. Duis scelerisque id mi et mollis. Nulla sit amet vehicula quam. Pellentesque nisi augue, rutrum ut ullamcorper vitae, mollis mollis ligula. In dolor orci, faucibus at finibus ornare, imperdiet vitae lectus. Praesent aliquet felis eget egestas maximus. Vestibulum vitae sapien tincidunt, posuere ex sed, scelerisque nulla.

    Nunc tempus nibh et nunc venenatis lacinia. Nulla facilisi. In fringilla justo magna, facilisis rutrum urna mollis ut. Phasellus et lorem cursus, luctus felis quis, dapibus orci. Nam non nulla nulla. Aenean luctus nisl sit amet porta pharetra. Suspendisse varius sed neque ac fringilla. Duis ornare odio id lorem tempor, ac condimentum nisi luctus. Aliquam erat volutpat..
</p>

Lab1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Владимирская область<br />
    Город Муром<br />
    ул.Орловская д.40<br />
    <abbr title="Phone">Телефон:</abbr>
    8-950-232-04-12
</address>

<address>
    <strong>Support:</strong>   <a href="mivlgu.ru">Support@example.com</a><br />
</address>

Lab1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Добро пожаловать на сайт общежития Ми ВлГУ";
}
<h2>Гостиница Зоря</h2>
<body>

    <div class="container body-content">
        <hr />
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#home">Информация о Нашей гостинице</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#profile">Наша история</a>
            </li>
            @if (User.IsInRole("Client"))
            {
                <li>
                    @Html.ActionLink("Наши номера", "Index", "Apartments")
                </li>
            }
            @if (User.IsInRole("Administrator"))
            {
                <li>
                    @Html.ActionLink("Клиенты", "Index", "Clients")
                </li>
                <li>
                    @Html.ActionLink("Проживаия", "Index", "Livings")
                </li>
                <li>
                    @Html.ActionLink("Брони", "Index", "Bookings")
                </li>
                <li>
                    @Html.ActionLink("Номера", "Index", "Apartments")
                </li>
                <li>
                    @Html.ActionLink("Типы номеров", "Index", "ApartmentType")
                </li>
                <li>
                    @Html.ActionLink("Типы дополнительных услуг", "Index", "AditionServices")
                </li>
                <li>
                    @Html.ActionLink("Наши номера", "Index", "Apartments")
                </li>
                <li>
                    @Html.ActionLink("Наши номера", "Index", "Apartments")
                </li>
            }
        </ul>
        <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade" id="home">
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean sit amet sem semper, laoreet augue nec, volutpat arcu. Sed commodo dui a nibh sagittis, ac faucibus eros congue. Quisque sodales, diam et facilisis cursus, lorem neque efficitur quam, eget imperdiet risus justo sit amet erat. Etiam dignissim dolor et mauris pulvinar luctus. Aenean tortor turpis, tincidunt a blandit non, eleifend sit amet tellus. Vestibulum eu nunc id eros porttitor lacinia. Duis faucibus sed sapien sed varius. Nulla facilisi. Praesent turpis urna, dapibus vitae vulputate mollis, varius eu sem.
                </p>
            </div>
            <div class="tab-pane fade active show" id="profile">
                <p>

                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut rutrum ante elit, eget tincidunt leo imperdiet et. Proin auctor semper aliquet. Donec dui urna, tristique non augue a, vulputate commodo justo. Suspendisse sit amet finibus velit. Aliquam sed magna neque. Sed lacinia tristique tellus, a tempor lorem euismod porta. Vivamus et faucibus nulla, at ultricies ex. Praesent ac arcu ultrices, ullamcorper erat in, mollis lacus. Vivamus imperdiet neque ac ipsum pretium sollicitudin.
                </p>
            </div>
        </div>
    </div>
</body>